[package]
name = "bascet-core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bascet-derive.workspace = true
bascet-variadic.workspace = true

bon.workspace = true
branches.workspace = true
bytesize.workspace = true
compio.workspace = true
hwlocality.workspace = true
crossbeam-queue.workspace = true
crossbeam-utils.workspace = true
derive_more.workspace = true
event-listener.workspace = true
inventory.workspace = true
kanal.workspace = true
memmap2.workspace = true
page_size.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bench]]
name = "bursty"
harness = false

[[bench]]
name = "parallel"
harness = false

[[bench]]
name = "tiers"
harness = false
